<div id="sub_content_panel" align="center">
    <div id="sub_bullet1" align="center"></div>
    <div id="sub_info" align="center">
    	<div align="left"><a id="content_sub_1" class="text_black_big" href="<?php echo $this->url(array('controller'=>'empresa', 'action'=>'index'),'default',true); ?>" onmouseover="changeStyleDivContentUp(1,0);" onmouseout="changeStyleDivContentDown(1);"><?php echo $this->translate("SUBCONT_EMPRESA");?></a></div>
        <div style="height:3px;"></div>
        <div align="left"><a id="content_sub_2" class="text_plomo_7_small" href="<?php echo $this->url(array('controller'=>'empresa', 'action'=>'index'),'default',true); ?>" onmouseover="changeStyleDivContentUp(1,0);" onmouseout="changeStyleDivContentDown(1);"><?php echo $this->translate("SUBCONT_EMPRESA_SUB");?></a></div>
    </div>
</div>
<div id="sub_content_panel" align="center">
    <div id="sub_bullet2" align="center"></div>
    <div id="sub_info" align="center">
    	<div align="left"><a id="content_sub_3" class="text_black_big" href="<?php echo $this->url(array('controller'=>'productos', 'action'=>'categorias'),'cart',true); ?>" onmouseover="changeStyleDivContentUp(2,0);" onmouseout="changeStyleDivContentDown(2);"><?php echo $this->translate("SUBCONT_PRODUCTOS");?></a></div>
        <div style="height:3px;"></div>
        <div align="left"><a id="content_sub_4" class="text_plomo_7_small" href="<?php echo $this->url(array('controller'=>'productos', 'action'=>'categorias'),'cart',true); ?>" onmouseover="changeStyleDivContentUp(2,0);" onmouseout="changeStyleDivContentDown(2);"><?php echo $this->translate("SUBCONT_PRODUCTOS_SUB");?></a></div>
    </div>
</div>
<div id="sub_content_panel" align="center">
    <div id="sub_bullet3" align="center"></div>
    <div id="sub_info" align="center">
    	<div align="left"><a id="content_sub_5" class="text_black_big" href="<?php echo $this->url(array('controller'=>'contactenos', 'action'=>'index'),'default',true); ?>" onmouseover="changeStyleDivContentUp(3,0);" onmouseout="changeStyleDivContentDown(3);"><?php echo $this->translate("SUBCONT_CONTACTO");?></a></div>
        <div style="height:3px;"></div>
        <div align="left"><a id="content_sub_6" class="text_plomo_7_small" href="<?php echo $this->url(array('controller'=>'contactenos', 'action'=>'index'),'default',true); ?>" onmouseover="changeStyleDivContentUp(3,0);" onmouseout="changeStyleDivContentDown(3);"><?php echo $this->translate("SUBCONT_CONTACTO_SUB");?></a></div>
    </div>
</div>