<div id="footer_content">    
    <div id="content-footer-1">
        <span class="text_blanco_small_2"><?php echo $this->translate("footer_desc");?></span>
    </div>
    <div id="content-footer-2" align="right">
        <iframe src="//www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.facebook.com%2Fpages%2Fvadimar-%2F153979308004378&amp;send=false&amp;layout=button_count&amp;width=120&amp;show_faces=false&amp;action=like&amp;colorscheme=dark&amp;font=arial&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:120px; height:21px;" allowTransparency="true"></iframe>
        <a href=" http://www.youtube.com/channel/UCTInm4VCcxnB92PuaEWWZMA/videos?view=0" target="_blank"><img src="<?php echo $this->baseUrl() . '/m_web/images/footer/youtube.png';?>" width="37" height="37" border="0" style="cursor:pointer;" /></a>
        <a href=" http://www.facebook.com/pages/Vadimar-Gourmet-Vadimar-SAC/236610806411110?fref=ts" target="_blank"><img src="<?php echo $this->baseUrl() . '/m_web/images/footer/facebook.png';?>" width="37" height="37" border="0" style="cursor:pointer;" /></a>
        <img src="<?php echo $this->baseUrl() . '/m_web/images/footer/twitter.png';?>" width="37" height="37" border="0" style="cursor:pointer;" />	
    </div>
</div>