<?php

namespace cart\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * CartUnidadMedidaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartUnidadMedidaRepository extends EntityRepository
{
}
