<?php

namespace web\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * CmsUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmsUserRepository extends EntityRepository
{
    /**
     * 
     * @param string $usuario
     * @param string $clave
     * @return \web\Entity\CmsUser
     */
    public function login($usuario, $clave) {
        $query = $this->_em->createQuery('SELECT u from \web\Entity\CmsUser u 
            WHERE u.nickUser = :user AND u.passUser = :clave AND u.stateUser=1');
        $query->setParameters(array(
            'user' => $usuario,
            'clave' => md5($clave)
        ));
        $users = $query->getResult();
        return isset($users[0])?$users[0]:null;
    }
    
    public function changeEmailClave($iduser, $email, $clave) {
        try {
            $oUser = new \web\Entity\CmsUser();
            $dqlList = 'SELECT u FROM \web\Entity\CmsUser u WHERE u.iduser = ?1';
            $qyUser = $this->_em->createQuery($dqlList);
            $qyUser->setParameter(1,$iduser);
            try {
                $oUser = $qyUser->getSingleResult();
            } catch(\Doctrine\ORM\NoResultException $e) {
                throw new \Exception('No existe este registro o no se encuentra disponible.',1);
            }
            if($email != "")
                $oUser->setEmailUser($email);
            if($clave != "")
                $oUser->setPassUser(md5($clave));
            
            $this->_em->persist($oUser);
            $this->_em->flush();
            return true;
        } catch(\Doctrine\ORM\NoResultException $e) {
            if ($e->getCode() == 1) throw new \Exception($e->getMessage(),1);
            throw new \Exception('Ocurrió un error en el procesamiento, estaremos solucionandolo en breve.',1);
        }
    }
    
}
